### ISSUE TITLE
Host setup is too early "RUN echo ${HOST_IP} > /setup_ips.txt"

### ISSUE THREAD

**Issue by jhannes** [schuellerf/docker-geneweb#1]
In `Dockerfile`, the line `RUN echo ${HOST_IP} > /setup_ips.txt` is evaluated when the image is built, not when it runs. This means that if the host-ip is not "172.17.0.1", `/start_setup.sh` will web deny access.

The fix is simple enough: Just add the line to `/start_setup.sh` instead (before `gwsetup`). :-)

**Comment by schuellerf** [comment]
I wanted to leave the `/setup_ips.txt` as part of the image to have a "default" setup if you start the container with "bash" and not with the default entry point. Nevertheless you were right and I added an option to override the IP. Is this ok for you?

**Comment by jhannes** [comment]
Works great! :+1:
