### ISSUE TITLE
ged2gwb doesn't work out of the box

### ISSUE THREAD

**Issue by jhannes** [schuellerf/docker-geneweb#2]
When using the /ged2gwb-command (for the management), the command `$ /usr/share/geneweb/ged2gwb -f /genewebData/foo.ged -o foo > comm.log` returns an error. Investigating further, it seems like ged2gwb isn't in the location that `gwsetup` assumes. The fix is easy enough. In the `Dockerfile` add this to the sequence of `RUN ln` commands:

  `RUN ln -s /usr/bin/ged2gwb /usr/share/geneweb/ged2gwb`

Cheers!

**Comment by schuellerf** [comment]
please check (I'd wish there was an issue-state for this...)

**Comment by jhannes** [comment]
Works! :-)
